Update accept.txt
stakater/vocabulary pull request #33
Opened 2023-02-01 10:56 UTC by MichaelLi202112

2023-02-01 11:22 UTC, callum-stakater submitted a review, later dismissed

2023-02-01 12:26 UTC, karl-johan-grahn requested changes

2023-02-01 12:26 UTC, karl-johan-grahn commented on styles/Vocab/Stakater/accept.txt
> +[Nn]etmaker
please sort in alphabetic order

2023-02-03 08:31 UTC, karl-johan-grahn approved these changes

2023-02-03 08:31 UTC, merged