added new spelling
stakater/vocabulary pull request #63
Opened 2023-10-19 23:20 UTC by tanalam2411

2023-10-20 05:48 UTC, karl-johan-grahn requested changes

2023-10-20 05:48 UTC, karl-johan-grahn commented on styles/Vocab/Stakater/accept.txt
> +[Kk]afka
add in alphabetical order

2023-10-20 20:09 UTC, tanalam2411 commented on styles/Vocab/Stakater/accept.txt
> +[Kk]afka
updated in alphabetical order

2023-10-23 06:48 UTC, karl-johan-grahn approved these changes

2023-10-23 06:48 UTC, merged